#!/usr/bin/env bash
# Configure your domain zone so that the subdomain will point to load balancer

function_domain(){

	if [ -n "$2" ]
    then
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v sd="$2" '{print "The subdomain " sd " is " $7 " record and points to " $8}'
    else
	dig "www.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain www is " $7 " record and points to " $8}'
	dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain lb-01 is " $7 " record and points to " $8}'
	dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-01 is " $7 " record and points to " $8}'
	dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-02 is " $7 " record and points to " $8}'
    fi
}


function_domain "$1" "$2"
