#!/usr/bin/env bash

# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

echo "

frontend http_front
   mode http
   bind *:80
   default_backend http_back

backend http_back

   mode http
   balance roundrobin
   server 156769-web-01 35.153.18.80:80 check
   server 156769-web-02 100.25.167.135:80 check" >> /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
sudo systemctl enable haproxy
