#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*
echo "ENABLED=1" >> /etc/default/haproxy
echo "
frontend http_front
   bind *:80
   mode http
   default_backend http_back

backend http_back
   balance roundrobin
   server 156769-web-01 35.153.18.80:80 check
   server 156769-web-02 100.25.167.135:80 check " >> /etc/haproxy/haproxy.cfg
service haproxy restart
