#!/usr/bin/env bash
# write's badluck at 4th and goodluck at 8th other Best School

i=0;

while [ $i -lt 10 ]
do
  if [ $i == 3 ]
  then
      echo "bad luck"
  elif [ $i == 7 ];
  then
      echo "good luck"
  else
      echo "Best School"
  fi

  ((i++))
done
